POST {{search_host}}/search/index/course
Content-Type: application/json

{
  "charge" : "201000",
  "companyId" : 100000,
  "companyName" : "中国队加油",
  "createDate" : "2024-07-25 09:36:11",
  "description" : "奥林匹克运动会",
  "grade" : "204001",
  "id" : 300,
  "mt" : "1-3",
  "mtName" : "spring中国奥运冠军",
  "name" : "spring中国奥运体育竞赛冠军",
  "originalPrice" : 200.0,
  "pic" : "/mediafiles/2022/09/14/a16da7a132559daf9e1193166b3e7f52.jpg",
  "price" : 100.0,
  "remark" : "没有备注",
  "st" : "1-3-2",
  "stName" : "越来越好",
  "status" : "203002",
  "tags" : "没有标签",
  "teachmode" : "200002",
  "validDays" : 222
}


### 搜索课程
GET {{search_host}}/search/course/list?pageNo=1&keywords=spring
Content-Type: application/json

### 添加课程索引
POST {{search_host}}/search/index/course
Content-Type: application/json

{
  "charge" : "201000",
  "companyId" : 100000,
  "companyName" : "巴黎奥运会",
  "createDate" : "2024-07-25 09:36:11",
  "description" : "更高更快更强",
  "grade" : "204001",
  "id" : 102,
  "mt" : "1-3",
  "mtName" : "spring体育运动",
  "name" : "spring体育竞赛",
  "originalPrice" : 200.0,
  "pic" : "/mediafiles/2022/09/23/db4e24f27d78ccac14401b7479b35c26.jpg",
  "price" : 100.0,
  "remark" : "没有备注",
  "st" : "1-3-2",
  "stName" : "哈哈哈",
  "status" : "203002",
  "tags" : "没有标签",
  "teachmode" : "200002",
  "validDays" : 222
}